---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#
#   fontname: myfont
#   fullname: MyFont
#   familyname: Myfont
#
#   height: 1000
#   ascent: 850
#   descent: -150
#   weight: "Regular"
#
#   Adjust t
#   scale: 0.7
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#
# glyphs:
#   - name: glyph_file            # file name, without extention
#     code: 0xNNN                 # Symbol code 0x - hex
#
################################################################################
#

meta:
  author: Nathakit Sae-Tan
  homepage: http://pupil-labs.com
  email: nat@pupil-labs.com
  github: http://github.com/pupil-labs/pupil-icon-font
  license: LGPL-3.0

font:
  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  version: "0.0.1"
  fontname: pupil_icons
  fullname: Pupil Icons
  familyname: Pupil
  copyright: Copyright (C) 2017 by Pupil Labs

  ascent: 850
  descent: -150
  weight: Normal
  scale: .7

glyphs:
  # material icons
  - fullname: general settings
    codename: gs
    code: 0xE8B8

  - fullname: plugin manager
    codename: pm
    code: 0xE8C0

  - fullname: active sources
    codename: as
    code: 0xE412

  - fullname: recorder
    codename: rec
    code: 0xE04B

  - fullname: groups
    codename: g
    code: 0xE886

  - fullname: remote
    codename: rm
    code: 0xE307

  - fullname: vis circle
    codename: vcl
    code: 0xE061

  - fullname: vis lightpoints
    codename: vlp
    code: 0xE3A5

  - fullname: vis polyline
    codename: vpl
    code: 0xE922

  - fullname: vis scan path
    codename: vsp
    code: 0xE422

  - fullname: annotation player
    codename: ap
    code: 0xE866

  - fullname: raw data exporter
    codename: rde
    code: 0xE873

  - fullname: marker auto trim marks
    codename: mat
    code: 0xE41F

  - fullname: system graph
    codename: sg
    code: 0xE01D

  - fullname: fast forward
    codename: f
    code: 0xE01F

  - fullname: fast rewind
    codename: r
    code: 0xE020

  - fullname: audio capture
    codename: ac
    code: 0xE029

  - fullname: play
    codename: p
    code: 0xE037

  - fullname: skip next
    codename: sn
    code: 0xE044

  - fullname: download
    codename: d
    code: 0xE2C5

  - fullname: blink detection
    codename: bd
    code: 0xE81A

  - fullname: pause
    codename: ps
    code: 0xE034

  - fullname: skip previous
    codename: sp
    code: 0xE045

  - fullname: audio playback
    codename: apb
    code: 0xE050

    # custom icons
  - fullname: saccade
    codename: sc
    code: 0xe8f5

  - fullname: source
    codename: s
    code: 0xEC01

  - fullname: vis eye video overlay
    codename: veo
    code: 0xEC02

  - fullname: vis fixation
    codename: vf
    code: 0xEC03

  - fullname: vis watermark
    codename: vwm
    code: 0xEC04

  - fullname: batch exporter
    codename: be
    code: 0xEC05

  - fullname: camera intrinsics estimation
    codename: cie
    code: 0xEC06

  - fullname: offline surface tracker
    codename: ost
    code: 0xEC07

  - fullname: manual gaze correction
    codename: mgc
    code: 0xEC08

  - fullname: video export launcher
    codename: vel
    code: 0xEC09

  - fullname: log history
    codename: lh
    code: 0xEC10

  - fullname: vis accuracy
    codename: vac
    code: 0xEC11

  - fullname: offline pupil detection
    codename: opd
    code: 0xEC12

  - fullname: vis cross
    codename: vcr
    code: 0xec13

  - fullname: offline calibration
    codename: c
    code: 0xEC14

  - fullname: time sync
    codename: ts
    code: 0xEC15

  - fullname: Remote recorder
    codename: rr
    code: 0xec16

  - fullname: frame publisher
    codename: fr
    code: 0xEC17

  - fullname: pupil detector 2d
    codename: pd2d
    code: 0xEC18

  - fullname: pupil detector 3d
    codename: pd3d
    code: 0xEC19

  - fullname: gaze mapper
    codename: gm
    code: 0xEC20

  - fullname: hololens relay
    codename: hlr
    code: 0xEC21

  - fullname: imu timeline
    codename: imu_timeline
    code: 0xEC22
